name: .NET Core Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64

    runs-on: ubuntu-latest

    env:
      Solution_Name: HtmlScrapper 
      Test_Project_Path: HtmlScrapperTests 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Execute unit tests
      run: dotnet test

    - name: Restore the application
      run: dotnet restore

    - name: Build
      shell: bash
      run: dotnet publish ./HtmlScrapper -c ${{ matrix.configuration }} -r ${{ matrix.target }} -o HtmlScrapper-${{ matrix.target }} --sc

    # - name: Help
    #   shell: bash
    #   run: |
    #     tree

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HtmlScrapper-${{ matrix.configuration }}-${{ matrix.target }}
        path: HtmlScrapper-${{ matrix.target }}/*
